name: Test CI/CD
run-name: Test CI/CD

on:
  push
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
      - run: npm install
      - run: npx prettier . --check

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'gatsby'
          path: '.'
          format: 'HTML'
      - name: Upload Test Results
        uses: actions/upload-artifact@master
        with:
          name: Dependency Check Report
          path: ${{github.workspace}}/reports

  njsscan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: nodejsscan scan
      - uses: ajinabraham/njsscan-action@master
        with:
          args: '.'

  build:
    runs-on: ubuntu-latest
    needs: [test, dependency-check, njsscan]
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.PAGES_ACCESS_TOKEN }}
          deploy-branch: "gh-pages"